name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  work:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:[ 16.x ]
    steps:
      - user: action/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v1
        with:
        node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm i
      - name: build project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit